function loadApplicationProblem(count, problemZone){
	pv = new ProblemView(problemZone, '应用题', 'LG')
	// pv.putProblem("小红有6支铅笔，小芳有4支铅笔，小红给了小芳2支铅笔，现在谁的铅笔多？多几支？")
	// pv.putProblem("小青有9本故事书，小新有7本连环画，小青用3本故事书换小新2本连环画，现在小青、小新各有几本书？")
	// pv.putProblem("小华有10个红气球，小花有8个黄气球。小华用4个红气球换小花3个黄气球，现在小华、小花各有几个球？")
	// pv.putProblem("爸爸，妈妈有一样多的糖果，爸爸给了妈妈3块糖后，谁的糖多一些？多几块？")
	// pv.putProblem("小华比小明多8支铅笔，小华要给小明多少支铅笔，他俩的铅笔才能一样多？")
	// pv.putProblem("哥哥给了弟弟2支铅笔后还剩5支，这时两人的铜笔一样多，弟弟原来有几支铅笔。")
	// pv.putProblem("两箱苹果都重40千克，从第一箱中拿出8千克到第二箱后，第二箱比第一箱多(__)千克。")
	// pv.putProblem("有两辆公交车，第一辆车上有18个人，第二辆车上有12个人，那么从第一辆车上分几个人到第二辆车上，两车的人数就相等了?")
	// pv.putProblem("妈妈有10块糖，给了Lulu两块后，她们俩的糖就一样多了，Lulu原来有几块糖？")
	// pv.putProblem("小朋友们排队，第一队有8个小朋友，从第二队过来3个小朋友后，两队的小朋友就一样多了，第二队原来有多少个小朋友？")
	// pv.putProblem("小白兔和小灰兔各有一些萝卜，小白兔给了小灰兔5个萝卜后，它们的萝卜就一样多了，原来小白兔比小灰兔多几个萝卜？")
	// pv.putProblem("开学时同学们领课本，小军领了19本书，小玲领了6本书，小刚也领了一些书，不知道有几本。这时，老师让小军给小玲4本书，并给小刚一些书，这时他们三个人的书就一样多了，那么小刚原来有几本书？")
	// pv.putProblem("哥哥4个苹果，姐姐有3个苹果，弟弟有8个苹果，哥哥给弟弟1个后，弟弟吃了3个，这时谁的苹果多？")
	

	// pv.putProblem("小明要做12道作业题，他做完了5道，还有几题要做？")
	// pv.putProblem("小明要做9道作业题，过了一会，他还剩4道题要做，小明已经做了几题数学题？")
	// pv.putProblem("小明和小华一起写作业，他们各有12道题要做，过了一会儿，小明做了9道题，小华做了7道题，小明比小华多做了几道题？")
	// pv.putProblem("小明和小华一起写作业，他们各有15道题要做，过了一会儿，小明还剩5道题，小华还剩8道题，小明比小华多做了几道题？")
	// pv.putProblem("姥姥和姥爷一起包饺子，他们一开始有一样多的饺子皮，过了一段时间以后，姥姥还剩10张饺子皮，姥爷还剩15张饺子皮，姥姥，姥爷谁包的饺子多？多多少？")
	// pv.putProblem("两段绳子一样长，用掉一些以后，第一根绳子还剩5米，第二根绳子还剩7米，那一段绳子用掉的比较多？多用多少米？")
	// pv.putProblem("小花和小丽去买文具，小花买了一支铅笔和一个本子花了5块钱，小丽买了一支铅笔和一把尺子，花了3块钱，本子和尺子哪个贵一些，贵多少？")
	// pv.putProblem("苹果比梨多24个，梨比桔子少25个，桔子和苹果哪个多，多几个？")
	// pv.putProblem("红绳子比蓝绳子长5米，绿绳子比蓝绳子短2米，红绳子长一些还是绿绳子长一些？长多少米？")

	// pv.putProblem("一辆空调车上有42人，中途下车8人，又上来16人，现在车上有多少人？")
	// pv.putProblem("公交车到站，下去3个人，上来5个人，公交车上的人是变多了还是变少了？多多少人或少多少人？")
	// pv.putProblem("公交车到站，下去3个人，上来5个人，现在车上有12个人，那么到站前，车上有多少个人？")
	// pv.putProblem("树上站着一些小鸟，飞来了3只，又飞来了3只，树上的小鸟变多了多少只？")

	// pv.putProblem("一部电影长80分钟，它在11:45结束，它是什么时候开始的？")
	// pv.putProblem("一节课35分钟长，10:15开始上课，什么时候下课？")
	// pv.putProblem("现在是18:35，Lulu要到19:00才能下楼玩，Lulu还要等多长时间才能下楼？")
	// pv.putProblem("Lulu从19:30开始看电影，到20:15时，Lulu看了多长时间的电视了？")
	// pv.putProblem("Lulu从18:45开始下楼玩儿，她可以在楼下玩1个小时，Lulu要几点上楼回家？")

	// pv.putProblem("爸爸买回来20个苹果和一些梨，吃了6个苹果后，梨比苹果还多3个，爸爸买回来多少个梨？")

	// var problem = $('<div>')
	// problem.append($('<p>张，黄，李分别是三个小朋友的姓，根据下面的三句话，请你猜一猜，三位小朋友分别姓什么？</p>'))
	// var list = $('<ol>')
	// list.append($('<li>甲不姓张</li>'))
	// list.append($('<li>姓黄的不是丙</li>'))
	// list.append($('<li>甲和乙正在听姓李的小朋友唱歌</li>'))
	// problem.append(list)
	// problem.append($('<p>甲乙丙三个小朋友分别姓什么？</p>'))
	// pv.putProblemHtmlElement(problem)

	// problem = $('<div>')
	// problem.append($('<p>王叔叔，李叔叔，宋叔叔他们一个是教师，一个是工人，还有一个是画家，已知：</p>'))
	// list = $('<ol>')
	// list.append($('<li>王叔叔比教师年龄大</li>'))
	// list.append($('<li>李叔叔和教师不同岁</li>'))
	// list.append($('<li>王叔叔和画家是朋友友</li>'))
	// problem.append(list)
	// problem.append($('<p>你猜他们分别是什么职业？</p>'))
	// pv.putProblemHtmlElement(problem)

	// problem = $('<div>')
	// problem.append($('<p>小猫，小兔，小狗的房子在一排</p>'))
	// list = $('<ol>')
	// list.append($('<li>小猫的房子在小兔房子右边5米的地方</li>'))
	// list.append($('<li>小狗的房子在小兔房子右边8米的地方</li>'))
	// problem.append(list)
	// problem.append($('<p>你知道谁住在最左边，谁住在最右边，谁住在中间？</p>'))
	// pv.putProblemHtmlElement(problem)

	// problem = $('<div>')
	// problem.append($('<p>有红色，黄色，蓝色三条绳子</p>'))
	// list = $('<ol>')
	// list.append($('<li>黄色的绳子比红色的绳子长3米</li>'))
	// list.append($('<li>蓝色的绳子比红色的绳子长5米</li>'))
	// problem.append(list)
	// problem.append($('<p>你知道哪根绳子最长？哪根绳子最短？</p>'))
	// pv.putProblemHtmlElement(problem)

	// problem = $('<div>')
	// problem.append($('<p>有三个小朋友，小红，小明，小丽</p>'))
	// list = $('<ol>')
	// list.append($('<li>小红比小明大3岁</li>'))
	// list.append($('<li>小丽比小红小2岁</li>'))
	// problem.append(list)
	// problem.append($('<p>你知道谁的年纪最小？谁的年纪最大？</p>'))
	// pv.putProblemHtmlElement(problem)

	problem = $('<div>')
	problem.append($('<p>有一些苹果，桔子和梨</p>'))
	list = $('<ol>')
	list.append($('<li>苹果比桔子多15个</li>'))
	list.append($('<li>桔子比梨少18个</li>'))
	problem.append(list)
	problem.append($('<p>你知道哪种水果最多？哪种水果最少？</p>'))
	problem.append($('<p>苹果和梨哪个多，多几个？</p>'))
	pv.putProblemHtmlElement(problem)

	problem = $('<div>')
	problem.append($('<p>小朋友一起分糖</p>'))
	list = $('<ol>')
	list.append($('<li>小红比小林多5块糖</li>'))
	list.append($('<li>小华比小红多2块糖</li>'))
	problem.append(list)
	problem.append($('<p>你知道谁的糖最多？小华比小林多几块糖？</p>'))
	pv.putProblemHtmlElement(problem)


	problem = $('<div>')
	problem.append($('<p>有一些苹果，桔子，梨和桃</p>'))
	list = $('<ol>')
	list.append($('<li>梨比桔子多10个</li>'))
	list.append($('<li>桔子比苹果少3个</li>'))
	list.append($('<li>梨比桃多2个</li>'))
	problem.append(list)
	problem.append($('<p>你知道哪种水果最多？哪种水果最少？</p>'))
	problem.append($('<p>苹果和桃哪个多，多几个？</p>'))
	pv.putProblemHtmlElement(problem)

	problem = $('<div>')
	problem.append($('<p>小朋友一起跳跳绳</p>'))
	list = $('<ol>')
	list.append($('<li>Lulu比豆豆多跳了28个</li>'))
	list.append($('<li>豆豆比明明少跳了10个</li>'))
	list.append($('<li>Lulu比茵茵多跳了12个</li>'))
	problem.append(list)
	problem.append($('<p>茵茵和明明谁跳得多？多几个？</p>'))
	pv.putProblemHtmlElement(problem)


	problem = $('<div>')
	problem.append($('<p>文具店里有橡皮，直尺，铅笔和剪刀</p>'))
	list = $('<ol>')
	list.append($('<li>剪刀比橡皮贵8元</li>'))
	list.append($('<li>橡皮比铅笔便宜5元</li>'))
	list.append($('<li>直尺比剪刀便宜4元</li>'))
	problem.append(list)
	problem.append($('<p>铅笔和直尺哪个贵，贵几元</p>'))
	pv.putProblemHtmlElement(problem)

	problem = $('<div>')
	problem.append($('<p>花园里有一些花</p>'))
	list = $('<ol>')
	list.append($('<li>红花比白花多15朵</li>'))
	list.append($('<li>黄花比白花多10朵</li>'))
	list.append($('<li>粉花比红花少8朵</li>'))
	problem.append(list)
	problem.append($('<p>粉花和黄花哪个多？多几朵？</p>'))
	pv.putProblemHtmlElement(problem)


	pv.putProblem("大林比小林多做15道口算题，小明比小林多做6道口算题，大林比小明多做几道口算题？")
	pv.putProblem("一只蜗牛向前爬25厘米，又朝后退15厘米，在朝前爬10厘米，结果前进了(___)厘米。")


	// pv.putProblem("一根铁丝用去一半后，再用去剩下的一半，这时剩下9米，原来这根铁丝多长？")
	// pv.putProblem("妈妈从家里到工厂要走3千米，一次，她上班走了2千米，又回家取一很重要工具，再到工厂。这次妈妈上班一共走了多少千米？")
	// pv.putProblem("小平家距学校2千米，一次他上学走了1千米，想起忘带铅笔盒，又回家去取。这次他到学校共走了多少千米？"
	// 	)


	// pv.putProblem("小明和小亮想买同一本书，小明缺1元7角，小亮缺1元3角。若用他们的钱合买这本书，钱正好。这本书的价钱是多少？他们各带了多少钱？")
	// pv.putProblem('小花今年6岁，爸爸对小花说："你长到10岁的时候，我正好40岁。"爸爸今年多少岁？')

	// pv.putProblem('把一杯水倒入空瓶，连瓶共重140克，如果倒入三杯水，连瓶共重260克。空瓶的重量是(___)克。')
}